version: "3.8"

services:
  portfolio-site:
    container_name: portfolio-site
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:80
    environment:
      NODE_ENV: production
    networks:
      - host