version: "3.8"

services:
  client:
    container_name: portfolio
    build:
      context: .
      dockerfile: dockerfile
      args:
        - GENERATE_SOURCEMAP=false
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - proxy

networks:
  proxy:
    external: true