version: "3.8"

networks:
  public:
    external: true

services:
  portfolio-site:
    image: portfolio
    container_name: portfolio
    restart: unless-stopped
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: dockerfile
    environment:
      NODE_ENV: production
    networks:
      - public
      