version: "3.8"

services:
  portfolio-site:
    image: portfolio
    container_name: portfolio-site
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:80
    environment:
      NODE_ENV: production
      
networks:
  default:
    name: proxy-network